### ISSUE TITLE
permalinks for headers not showing for asciidoc

### ISSUE THREAD

**Issue by capsulecorplab** [thegeeklab/hugo-geekdoc#152]
clickable permalinks next to headers appear for markdown-generated html, but not for asciidoc. See [example](https://303adastra.github.io/clockdriveos/tutorials/getting-started/) and [commit](https://github.com/303adastra/clockdriveos/commit/aeb1849e9a50bc382c1722265ff7afe2ea9dfc52).

**Comment by xoxys** [comment]
Thanks for your report. I'm very sorry about this, but that because the asciidoc support in Hugo itself is very limited -.- We use markup [render hooks](https://gohugo.io/getting-started/configuration-markup/) to customize the rendering of images links and headlines. You might see other formatting issues for images and links as well. 

As there is not really a good way to handle this for asciidoc I have to mark this issue as wontfix.

**Comment by capsulecorplab** [comment]
That's rather unfortunate, but I appreciate the response. Will take this under advisement.
