### ISSUE TITLE
Required node version

### ISSUE THREAD

**Issue by GaetanLepage** [thegeeklab/hugo-geekdoc#367]
Is there a specific reason the `node` version must not exceed 16 (`<17`) ?
Indeed, it is not very convenient to install a specific (older) version in some environments.

**Comment by xoxys** [comment]
Thanks for your request. We had some issues because people use older versions, that's why we started to limit it. As we will always use (and support) the latest LTS version, the current Non-LTS version was excluded as well.

If you still want to use another (older or newer) Node version, you are free to do so by overriding https://github.com/thegeeklab/hugo-geekdoc/blob/main/.npmrc#L3 or set the `engine-strict` via npm cli.

**Comment by GaetanLepage** [comment]
Ok ! Thank you very much for this precision :)
