### ISSUE TITLE
Toc conflicts with Hugo 0.60

### ISSUE THREAD

**Issue by signalogic** [thegeeklab/hugo-geekdoc#9]
Hugo 0.60 uses Goldmark as its default markdown library, and defines a TableOfContents page variable. This makes the Geekdoc ToC fail ... can you create  a different page var (maybe TableOfContents_Geekdoc) and provide a shortcode with if-else that allows both ToCs to be used ?

Thanks.

**Comment by xoxys** [comment]
Thanks for your report. Can you provide some more details in which situations the toc fail? The current toc shortcode is just a wrapper around the default TableOfContents of the current page provided by Goldmark.

**Comment by signalogic** [comment]
Ok I think it does work.  First I added to [Params] section of config.toml:

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1

then added a "TableOfContents_Geekdoc" param in the page's frontmatter, then put this in toc.html shortcode:

{{ if .Page.Params.TableOfContents_Geekdoc }}
  {{ $tocLevels := default (default 6 .Site.Params.GeekdocToC) .Page.Params.GeekdocToC }}

  <div class="gdoc-toc gdoc-toc__level--{{$tocLevels}}">{{ .Page.TableOfContents }}<hr></div>

{{ else }}  {{/* default Hugo Toc */}}

  <div>{{ .Page.TableOfContents }}<hr></div>  {{/* note that .TableOfContents is built-in Hugo var */}}

{{ end }}

Both ways work, I don't see any difference.  What would the gdoc-toc class do or display differently ?

Thanks. Sorry to reply slow.

**Comment by xoxys** [comment]
I don't really understand why you have added a `TableOfContents_Geekdoc` variable. The ToC is provided by the in-build page variable `.Page.TableOfContents`. You could completely ignore the `toc` shortcode and use `.Page.TableOfContents` directly in your markdown files. If you want to configure the ToC you could use:

```
[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1
```
The shortcode is just a second way to add a ToC to your markdown pages and has some small benefits:

- it is wrapped by a `div` block and has it's own CSS classes which could be used to customize how the ToC looks like
- it adds a small horizontal line at the bottom of the ToC to separate it from the content
- it will place the ToC at whatever position you want it to be on the page
- it has it's own CSS based way to define the ToC level depth because the old markdown renderer was not able to configure the ToC, this feature was introduced by Goldmark

So in general you have two ways to use the ToC. You could choose between the shortcode wrapper or the plain build-in `.Page.TableOfContents` variable. You could also choose between the methods to control the ToC depth. One option is to use the default Goldmark config options (see above) or the custom CSS solution controlled by the `GeekdocToC` variable but this one only works with the shortcode because it required the injected CSS classes `gdoc-toc gdoc-toc__level--*`. For example `GeekdocToC = 3` will display ToC level 1-3.

**Comment by signalogic** [comment]
I added the var for testing purposes, just to quickly switch back and forth (see the first {{if ... }} in toc.html.

Thanks for the benefits list. Being able to control depth level and place the toc as needed are definitely useful.

You mention injected classes. I found the .gdoc-toc{} definition in _base.scss but where are the __level--N classes defined ?

Thanks.

**Comment by xoxys** [comment]
It's also in `_base.scss` https://github.com/thegeeklab/hugo-geekdoc/blob/master/src/sass/_base.scss#L462.

**Comment by signalogic** [comment]
Ok got it. I needed to bone up on the "&" selector.

**Comment by xoxys** [comment]
As you can see on the file ending thats SASS syntax. I'm going to close the issue.
